# Generated by Django 2.2.13 on 2020-12-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100, null=True)),
                ('units', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('no_adult', models.IntegerField()),
                ('no_child', models.IntegerField()),
                ('no_room', models.IntegerField()),
                ('no_extra_bed', models.IntegerField()),
                ('account_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='reservation.Room')),
            ],
            options={
                'db_table': 'reservation',
                'managed': True,
            },
        ),
    ]
